/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as PorownanieRouteImport } from './routes/porownanie'
import { Route as PostulatyRouteImport } from './routes/postulaty'
import { Route as RachunekRouteImport } from './routes/rachunek'
import { Route as SkalaRouteImport } from './routes/skala'
import { Route as ProgramIndexRouteImport } from './routes/program/index'
import { Route as ProgramSlugRouteImport } from './routes/program/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const PorownanieRoute = PorownanieRouteImport.update({
  id: '/porownanie',
  path: '/porownanie',
  getParentRoute: () => rootRouteImport,
} as any)
const PostulatyRoute = PostulatyRouteImport.update({
  id: '/postulaty',
  path: '/postulaty',
  getParentRoute: () => rootRouteImport,
} as any)
const RachunekRoute = RachunekRouteImport.update({
  id: '/rachunek',
  path: '/rachunek',
  getParentRoute: () => rootRouteImport,
} as any)
const SkalaRoute = SkalaRouteImport.update({
  id: '/skala',
  path: '/skala',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramIndexRoute = ProgramIndexRouteImport.update({
  id: '/program/',
  path: '/program/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramSlugRoute = ProgramSlugRouteImport.update({
  id: '/program/$slug',
  path: '/program/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o-nas': typeof ONasRoute
  '/porownanie': typeof PorownanieRoute
  '/postulaty': typeof PostulatyRoute
  '/rachunek': typeof RachunekRoute
  '/skala': typeof SkalaRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/program/': typeof ProgramIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o-nas': typeof ONasRoute
  '/porownanie': typeof PorownanieRoute
  '/postulaty': typeof PostulatyRoute
  '/rachunek': typeof RachunekRoute
  '/skala': typeof SkalaRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/program': typeof ProgramIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/o-nas': typeof ONasRoute
  '/porownanie': typeof PorownanieRoute
  '/postulaty': typeof PostulatyRoute
  '/rachunek': typeof RachunekRoute
  '/skala': typeof SkalaRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/program/': typeof ProgramIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/o-nas'
    | '/porownanie'
    | '/postulaty'
    | '/rachunek'
    | '/skala'
    | '/program/$slug'
    | '/program/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/o-nas'
    | '/porownanie'
    | '/postulaty'
    | '/rachunek'
    | '/skala'
    | '/program/$slug'
    | '/program'
  id:
    | '__root__'
    | '/'
    | '/o-nas'
    | '/porownanie'
    | '/postulaty'
    | '/rachunek'
    | '/skala'
    | '/program/$slug'
    | '/program/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ONasRoute: typeof ONasRoute
  PorownanieRoute: typeof PorownanieRoute
  PostulatyRoute: typeof PostulatyRoute
  RachunekRoute: typeof RachunekRoute
  SkalaRoute: typeof SkalaRoute
  ProgramSlugRoute: typeof ProgramSlugRoute
  ProgramIndexRoute: typeof ProgramIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porownanie': {
      id: '/porownanie'
      path: '/porownanie'
      fullPath: '/porownanie'
      preLoaderRoute: typeof PorownanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postulaty': {
      id: '/postulaty'
      path: '/postulaty'
      fullPath: '/postulaty'
      preLoaderRoute: typeof PostulatyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rachunek': {
      id: '/rachunek'
      path: '/rachunek'
      fullPath: '/rachunek'
      preLoaderRoute: typeof RachunekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skala': {
      id: '/skala'
      path: '/skala'
      fullPath: '/skala'
      preLoaderRoute: typeof SkalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/': {
      id: '/program/'
      path: '/program'
      fullPath: '/program/'
      preLoaderRoute: typeof ProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$slug': {
      id: '/program/$slug'
      path: '/program/$slug'
      fullPath: '/program/$slug'
      preLoaderRoute: typeof ProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ONasRoute: ONasRoute,
  PorownanieRoute: PorownanieRoute,
  PostulatyRoute: PostulatyRoute,
  RachunekRoute: RachunekRoute,
  SkalaRoute: SkalaRoute,
  ProgramSlugRoute: ProgramSlugRoute,
  ProgramIndexRoute: ProgramIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
